import type { Expert } from "@/types/expert"
export const conversations = [
    {
      id: "1",
      name: "Isah Hassan",
      avatar: "/thoughtful-spectacled-man.png",
      lastMessage: "Hi everyone, could you share a brief status on our project? Looking forward to hearing from you!",
      timestamp: "12:30pm",
      unread: 1,
      archived: false,
      lastOnline: "20 hours ago",
      messages: [
        {
          id: "m1",
          content: "Hi everyone, could you share a brief status on our project? Looking forward to hearing from you!",
          timestamp: "12:30pm",
          sender: "other",
        },
        {
          id: "m2",
          content: "What excites you about this industry and what are the main challenges you have faced?",
          timestamp: "Now",
          sender: "other",
        },
        {
          id: "m3",
          content: "What excites you about this industry and what are the main challenges you have faced?",
          timestamp: "Now",
          sender: "user",
          read: true,
        },
      ],
    },
    {
      id: "2",
      name: "Maya Lin",
      avatar: "/confident-asian-leader.png",
      lastMessage: "The project is on track, but we need to finalize the budget.",
      timestamp: "1:15pm",
      unread: 1,
      archived: false,
      messages: [
        {
          id: "m1",
          content: "Hi, I wanted to check in about the project timeline.",
          timestamp: "Yesterday",
          sender: "other",
        },
        {
          id: "m2",
          content: "The project is on track, but we need to finalize the budget.",
          timestamp: "1:15pm",
          sender: "other",
        },
      ],
    },
    {
      id: "3",
      name: "Raj Patel",
      avatar: "/confident-indian-professional.png",
      lastMessage: "I have some updates regarding the vendor selection. Can we discuss?",
      timestamp: "1:45pm",
      unread: 1,
      archived: false,
      messages: [
        {
          id: "m1",
          content: "I have some updates regarding the vendor selection. Can we discuss?",
          timestamp: "1:45pm",
          sender: "other",
        },
      ],
    },
    {
      id: "4",
      name: "Emily Tran",
      avatar: "/joyful-portrait.png",
      lastMessage: "Thanks for the reminder, Isah. I'll send over the latest timelines shortly.",
      timestamp: "2:00pm",
      unread: 1,
      archived: false,
      messages: [
        {
          id: "m1",
          content: "Thanks for the reminder, Isah. I'll send over the latest timelines shortly.",
          timestamp: "2:00pm",
          sender: "other",
        },
      ],
    },
    {
      id: "5",
      name: "Isah Hassan",
      avatar: "/thoughtful-spectacled-man.png",
      lastMessage: "Hi everyone, could you share a brief status on our project? Looking forward to hearing from you!",
      timestamp: "12:30pm",
      unread: 0,
      archived: true,
      messages: [
        {
          id: "m1",
          content: "Hi everyone, could you share a brief status on our project? Looking forward to hearing from you!",
          timestamp: "12:30pm",
          sender: "other",
        },
      ],
    },
  ]
  
  

  // Mock data for experts
  const mockExperts: Expert[] = [
    {
      id: 1,
      name: "Muhammad Basheer",
      category: "Design",
      role: "Product Designer",
      skills: ["Figma", "Illustration", "AfterEffect", "Blender"],
      image: "/professional-man-glasses.png",
      rating: 4.9,
      reviews: 124,
      location: "New York, USA",
      hourlyRate: 45,
      isAvailable: true,
      responseTime: "fast",
      joinedDate: "January 2022",
      experienceLevel: "expert",
      about:
        "Experienced product designer with over 5 years of experience in UI/UX design, wireframing, and prototyping.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 123-4567",
      portfolio: [
        {
          title: "E-commerce App Redesign",
          description: "Complete redesign of a popular e-commerce platform",
          image: "/ecommerce-app-design.png",
        },
        {
          title: "Banking Dashboard",
          description: "User-friendly dashboard for a financial institution",
          image: "/banking-dashboard.png",
        },
      ],
    },
    {
      id: 2,
      name: "Muhammad Basheer",
      category: "Design",
      role: "Graphic Designer",
      skills: ["Adobe Photoshop", "Illustration", "AfterEffect", "Blender"],
      image: "/professional-man-glasses.png",
      rating: 4.8,
      reviews: 98,
      location: "San Francisco, USA",
      hourlyRate: 40,
      isAvailable: false,
      responseTime: "24h",
      joinedDate: "March 2021",
      experienceLevel: "intermediate",
      about: "Creative graphic designer with a passion for creating visually stunning designs.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 987-6543",
      portfolio: [
        {
          title: "Brand Identity for Tech Startup",
          description: "Complete brand package including logo and style guide",
          image: "/brand-identity-design.png",
        },
        {
          title: "Marketing Campaign Visuals",
          description: "Series of social media graphics for product launch",
          image: "/marketing-campaign-visuals.png",
        },
      ],
    },
    {
      id: 3,
      name: "Muhammad Basheer",
      category: "Project Management",
      role: "IT Project Manager",
      skills: ["Program Management", "Agile Project Management"],
      image: "/placeholder.svg?key=x30ci",
      rating: 4.7,
      reviews: 87,
      location: "London, UK",
      hourlyRate: 55,
      isAvailable: true,
      responseTime: "fast",
      joinedDate: "June 2020",
      experienceLevel: "expert",
      about: "Certified project manager with expertise in IT project delivery.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [
        {
          title: "Enterprise CRM Implementation",
          description: "Led the implementation of a CRM system for a Fortune 500 company",
          image: "/crm-implementation.png",
        },
      ],
    },
    {
      id: 4,
      name: "Muhammad Basheer",
      category: "Project Management",
      role: "IT Project Manager",
      skills: ["Program Management", "Agile Project Management"],
      image: "/placeholder.svg?key=99epa",
      rating: 4.5,
      reviews: 76,
      location: "Berlin, Germany",
      hourlyRate: 50,
      isAvailable: true,
      responseTime: "24h",
      joinedDate: "August 2021",
      experienceLevel: "expert",
      about: "Experienced project manager with a track record of successful IT implementations.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
    {
      id: 5,
      name: "Muhammad Basheer",
      category: "Development",
      role: "Frontend Developer",
      skills: ["React", "Next.js", "Tailwind CSS"],
      image: "/placeholder.svg?key=8r0pt",
      rating: 4.9,
      reviews: 135,
      location: "Toronto, Canada",
      hourlyRate: 60,
      isAvailable: false,
      responseTime: "24h",
      joinedDate: "May 2019",
      experienceLevel: "expert",
      about: "Senior frontend developer specialized in React ecosystem.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
    {
      id: 6,
      name: "Muhammad Basheer",
      category: "Development",
      role: "Backend Developer",
      skills: ["Node.js", "Express", "MongoDB"],
      image: "/placeholder.svg?key=sk7ub",
      rating: 4.7,
      reviews: 92,
      location: "Sydney, Australia",
      hourlyRate: 55,
      isAvailable: true,
      responseTime: "fast",
      joinedDate: "January 2020",
      experienceLevel: "intermediate",
      about: "Backend developer with strong skills in database design and API development.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
    {
      id: 7,
      name: "Muhammad Basheer",
      category: "Marketing",
      role: "Digital Marketer",
      skills: ["SEO", "Content Marketing", "Social Media"],
      image: "/placeholder.svg?key=ud942",
      rating: 4.6,
      reviews: 68,
      location: "Chicago, USA",
      hourlyRate: 45,
      isAvailable: true,
      responseTime: "24h",
      joinedDate: "March 2021",
      experienceLevel: "junior",
      about: "Digital marketing professional with focus on organic growth strategies.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
    {
      id: 8,
      name: "Muhammad Basheer",
      category: "Design",
      role: "UI/UX Designer",
      skills: ["Figma", "Adobe XD", "Sketch"],
      image: "/placeholder.svg?key=ec2lu",
      rating: 4.8,
      reviews: 112,
      location: "Amsterdam, Netherlands",
      hourlyRate: 50,
      isAvailable: false,
      responseTime: "24h",
      joinedDate: "September 2020",
      experienceLevel: "intermediate",
      about: "UI/UX designer with a passion for creating intuitive and beautiful interfaces.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
    {
      id: 9,
      name: "Muhammad Basheer",
      category: "Content",
      role: "Content Writer",
      skills: ["Blog Writing", "Copywriting", "SEO Writing"],
      image: "/placeholder.svg?key=0o0ef",
      rating: 4.5,
      reviews: 73,
      location: "Paris, France",
      hourlyRate: 40,
      isAvailable: true,
      responseTime: "fast",
      joinedDate: "July 2021",
      experienceLevel: "entry",
      about: "Content writer specializing in technology and business topics.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
    {
      id: 10,
      name: "Muhammad Basheer",
      category: "Development",
      role: "Full Stack Developer",
      skills: ["React", "Node.js", "PostgreSQL"],
      image: "/placeholder.svg?key=0o0ef",
      rating: 4.9,
      reviews: 156,
      location: "Austin, USA",
      hourlyRate: 65,
      isAvailable: false,
      responseTime: "24h",
      joinedDate: "April 2018",
      experienceLevel: "expert",
      about: "Full stack developer with expertise in building scalable web applications.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
    {
      id: 11,
      name: "Muhammad Basheer",
      category: "Design",
      role: "Motion Designer",
      skills: ["After Effects", "Cinema 4D", "Animation"],
      image: "/placeholder.svg?key=0o0ef",
      rating: 4.7,
      reviews: 89,
      location: "Tokyo, Japan",
      hourlyRate: 55,
      isAvailable: true,
      responseTime: "24h",
      joinedDate: "October 2019",
      experienceLevel: "intermediate",
      about: "Motion designer with a background in 3D animation and visual effects.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
    {
      id: 12,
      name: "Muhammad Basheer",
      category: "Marketing",
      role: "PPC Specialist",
      skills: ["Google Ads", "Facebook Ads", "Analytics"],
      image: "/placeholder.svg?key=0o0ef",
      rating: 4.6,
      reviews: 78,
      location: "Miami, USA",
      hourlyRate: 50,
      isAvailable: true,
      responseTime: "fast",
      joinedDate: "February 2020",
      experienceLevel: "expert",
      about: "PPC specialist with a proven track record of running successful ad campaigns.",
      email: "muhammad.basheer@example.com",
      phone: "+1 (555) 456-7890",
      portfolio: [],
    },
  ]
  
  export async function getExperts(): Promise<Expert[]> {
    // In a real application, this would fetch from an API
    return mockExperts
  }
  
  export async function getExpertById(id: number): Promise<Expert | undefined> {
    // In a real application, this would fetch a single expert from an API
    return mockExperts.find((expert) => expert.id === id)
  }
  
  export async function getExpertsByCategory(category: string): Promise<Expert[]> {
    // In a real application, this would fetch experts filtered by category from an API
    if (category === "all") return mockExperts
    return mockExperts.filter((expert) => expert.category === category)
  }
  
